name: assignment
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # firestore - data base
  cloud_firestore: ^5.1.0
  #firebase notification
  firebase_messaging: ^15.0.3

  #Firebse - backend
  firebase_core: ^3.2.0

  # GetX - state management
  get: ^4.6.6
  # Get Storage - Local storage
  get_storage: ^2.1.1
  # for calling
  zego_uikit_prebuilt_call: ^4.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
